<a href="https://colab.research.google.com/github/aminejguirim/artificial-intelligence-GoMyCode-/blob/main/seance2_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=2
y=6
x+y
print("the result is", x+y)  #the result is 8
x-y
print("the result is", x-y)  #the result is -4
x*y
print("the result is", x*y)  #the result is 12
y/x
print("the result is", y/x)  #the result is 3.0
y**x
print("the result is", y**x)  #the result is 36
y%x
print("the result is", y%x)  #the result is 0

the result is 8
the result is -4
the result is 12
the result is 3.0
the result is 36
the result is 0


In [ ]:
#operation bolean
(5!=7) == (2>1)
#1 != 5   #it returns True
#1 != 1   #it returns False

True

In [ ]:
a=(1!=5)
if a:
  print("bonjour")

bonjour


In [ ]:
type(a)

bool

In [ ]:
age=19
age_min=20
if( age < age_min) :
  print("omor")
  print(age)#this instruction is not inculded in the statment

omor
19


In [ ]:
age=20
age_min=19
if( age > age_min) :
  print("omor")
else:
  print(taha)

omor


In [ ]:
#LISTE
mylist=["amine","jguirim","23"]
print(mylist[0])

amine


In [ ]:
mylist=["amine","jguirim",[1,2]]
print(len(mylist[0]))#To determine how many items a list has, use the len() method:

5


In [ ]:
mylist=["amine","jguirim",[1,2]]
mylist[1]="Mobile"#To modify the value of a specific item, refer to the index number:
print(mylist)
mylist.append("web")#To add an item at the end of the list, use the append method:
print(mylist)
mylist.insert(1, "game")#Insert an item at the second position:
print(mylist)
mylist.remove("web")#The remove() method removes the specified item:
print(mylist)
del mylist[0]#The del keyword removes the specified index:
print(mylist)

['amine', 'Mobile', [1, 2]]
['amine', 'Mobile', [1, 2], 'web']
['amine', 'game', 'Mobile', [1, 2], 'web']
['amine', 'game', 'Mobile', [1, 2]]
['game', 'Mobile', [1, 2]]


In [ ]:
#Tuples
mytuple=("AI","Data Science", "Web")
print(mytuple)
print(mytuple[0])
print(len(mytuple))#To determine how many items a tuple has, use the len() method:
new_tuple=tuple("Carmichael")#It is also possible to use the tuple() constructor to create a tuple:  
new_tuple

('AI', 'Data Science', 'Web')
AI
3


('C', 'a', 'r', 'm', 'i', 'c', 'h', 'a', 'e', 'l')

In [ ]:
MyDict={"Name":"Jack", "Last Name":"Mccay", "year": 1964}
MyDict
pairs = {1: "apple", "orange": [2, 3, 4],  True: False, None: "True"}  
print(pairs)
variable=MyDict["Name"]#it returns the value of the key "Name" which is 'Jack''
print(variable)
variable=MyDict.get('Name')   #here we use the get method to get the value of Name
variable
MyDict['year']=2019   #changing the value of the key "year"
MyDict
MyDict.keys()  #it returns the keys of the dictionary :  dict_keys(['Name', 'Last Name', 'year'])
MyDict.values()  #it returns the values of the dictionary :  dict_values(['Jack', 'Mccay', 2019])
MyDict.items()   #it returns both keys and values: dict_items([('Name', 'Jack'), ('Last Name', 'Mccay'), ('year', 2019)])
MyDict={"Name":"Jack", "Last Name":"Mccay", "year": 2019}
MyDict['Survived']='Yes'   #adding new element (new key and new value)
MyDict   #it returns the new dictionary: {'Last Name': 'Mccay', 'Name': 'Jack', 'Survived': 'Yes', 'year': 2019}

{1: False, 'orange': [2, 3, 4], None: 'True'}
Jack


{'Last Name': 'Mccay', 'Name': 'Jack', 'Survived': 'Yes', 'year': 2019}

In [ ]:
#Boucles : for
MyList=['ai', 'data']
for x in MyList:
  print(x)
for x in range(4):#First Example: Starts from 0 to 4-1=3 incrementing by 1.
    print(x)
for x in range(1, 4):#Second Example: Starts from 1 to 4-1=3 incrementing by 1.
    print(x)
for x in range(2, 20, 3):#Third Example: Starts at 2 to 20-1=19 incrementing by 3.
    print(x)

ai
data
0
1
2
3
1
2
3
2
5
8
11
14
17
2


In [ ]:
#while
i=1
while i<6:
    print(i)
    i+=1

1
2
3
4
5


In [ ]:
counter = 0
while counter<3:
    print("Inside loop")
    counter = counter + 1
else:
    print("Inside else")

Inside loop
Inside loop
Inside loop
Inside else


In [ ]:
def my_function():#Une fonction est définie à l'aide du mot clé def :
    print("Hello from a function")
my_function()

Hello from a function


In [ ]:
def my_function(parameter):
    print("I want to learn "+parameter)
my_function("to code!")
my_function("to do AI!")

I want to learn to code!
I want to learn to do AI!


In [ ]:
def my_function(first_parameter, second_parameter):
    print("First parameter: "+first_parameter)
    print("Second parameter: "+second_parameter)
my_function("Hey", "you!")

First parameter: Hey
Second parameter: you!


In [ ]:
def my_function(country="Tunisia"):
    print("I am from "+country)
my_function("Maroc")
my_function("Algeria")
my_function()

I am from Maroc
I am from Algeria
I am from Tunisia


In [ ]:
def my_function(x):#To return a value from a function we can use the return statement :
    return 5*x
print(my_function(0))
print(my_function(1))
print(my_function(2))

0
5
10


In [ ]:
sum = lambda a,b,c : a+b+c
print(sum(8,3,5)) 

16


In [1]:
year = lambda ch : ch[:4]
ch = "20200310"
print(year(ch)) #2020

2020


In [2]:
test = lambda date : date.split('/')[1]
date = '2020/03/10'
print(test(date))

03


In [ ]:
#Matrice
import numpy as np
new_array=np.array([[1,2,3],[2,5,5]])
print(new_array)
print(new_array.shape)#To obtain the shape of “new_array”, use the command .shape(nbrligne et colonnes)
print(type(new_array))
print(new_array[0,:])
print(new_array[0,0])
print(new_array[:,0])


[[1 2 3]
 [2 5 5]]
(2, 3)
<class 'numpy.ndarray'>
[1 2 3]
1
[1 2]


In [ ]:
import numpy as np
new_array=np.random.randint(2,5,[3,6])
print(new_array)

[[4 3 3 3 3 2]
 [2 3 4 2 3 4]
 [3 2 2 3 3 2]]


In [ ]:
import numpy as np
new_array=np.random.random([3,6])
print(new_array)

[[0.91938964 0.96418356 0.33148862 0.09239977 0.18703382 0.43458197]
 [0.67981373 0.5037856  0.19507055 0.41949943 0.57147062 0.61130195]
 [0.40026172 0.78397162 0.72611548 0.86205312 0.78033822 0.9781016 ]]


In [ ]:
import numpy as np #Zeros function returns a new array of a given shape and type filled with zeros:
new_array=np.zeros([2,3])
print(new_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np #Full function returns a new array of a given shape and type filled with fill_value :
new_array=np.full(2,3)
print(new_array)

[3 3]


In [ ]:
import numpy as np #Eye function returns a 2D array with ones on the diagonal and zeros elsewhere :
new_array=np.eye(5)
print(new_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np #Ones function returns a new array of given shape and type filled with ones :
new_array=np.ones((5,5))
print(new_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
import numpy as np
new_array=np.random.randint(2,5,[3,6])
print(new_array)
new_array2=np.random.randint(2,5,[3,6])
print(new_array2)
new_array3=np.add(new_array,new_array2)#The function add returns the sum of two arrays:
print(new_array3)
new_array3=np.subtract(new_array,new_array2)#The function subtract returns the difference between two numpy arrays
print(new_array3)

[[3 3 2 3 2 2]
 [2 2 2 2 3 4]
 [2 4 2 4 4 4]]
[[4 2 2 4 2 4]
 [2 2 2 3 4 3]
 [2 4 4 4 3 3]]
[[7 5 4 7 4 6]
 [4 4 4 5 7 7]
 [4 8 6 8 7 7]]
[[-1  1  0 -1  0 -2]
 [ 0  0  0 -1 -1  1]
 [ 0  0 -2  0  1  1]]


In [ ]:
import numpy as np
new_array=np.array([[2,5],[3,6],[2,3]])
bool_idx=(new_array>2)
print(bool_idx)
print(new_array[bool_idx])
print(bool_idx)
print(new_array[new_array>2])

[[False  True]
 [ True  True]
 [False  True]]
[5 3 6 3]
[[False  True]
 [ True  True]
 [False  True]]
[5 3 6 3]


In [4]:
import numpy as np
new_array=np.array([[2,5],[3,6],[2,3]])
for i in new_array
print (new_array(1,0))

SyntaxError: ignored

In [5]:
a = np.array([[9, 18], [19, 10]])
print( a > 10)

[[False  True]
 [ True False]]
